version: '3.9'
services:
    # Bases de datos
    mysql_bd_Personas:
        image: mysql/mysql-server:latest
        ports:
            - "3307:3306"
        restart: always
        volumes:
            - bd_volumen_personas/var/lib/mysql
            - ./BaseDatosDocker/CREATE_Personas_script.sql:/docker-entrypoint-initdb.d/CREATE_Personas_script.sql:ro
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci']
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_HOST: localhost
            MYSQL_DATABASE: "Personas"
            MYSQL_USER: "root"
            # MYSQL_USER: "usuario"
            # MYSQL_PASSWORD: "PASS333"
        container_name: bd_personas

#    simple_app:
#        image: app_consola_personas
#        depends_on: 
#            - "mysql_inventario"
#        build: 
#            context: ./inventario/
#            dockerfile: Dockerfile
#        environment: 
#            DB_CONNECTION_STRING: "server=localhost;port=3307;user=admin;password=admin;database=inventario"
#        container_name: app_inventario

volumes:
  bd_volumen_personas: