version: '3.9'
services:
    # Bases de datos
    mysql_bd_Personas:
        image: mysql/mysql-server:latest
        container_name: bd_personas
        ports:
            - "3310:3306"
        restart: always
        volumes:
            - bd_volumen_personas:/var/lib/mysql
            - ./BaseDatosDocker/CREATE_Personas_script.sql:/docker-entrypoint-initdb.d/CREATE_Personas_script.sql:ro
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci']
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_HOST: localhost
            MYSQL_DATABASE: "Personas"
            MYSQL_USER: "root"
        

#    app de consola
    app-consola:
        image: app-consola
        container_name: contenedor-consola
        build: 
            context: ./AppConsola/
            dockerfile: Dockerfile
        stdin_open: true 
        tty: true  
        depends_on: 
            - "mysql_bd_Personas"
        environment: 
            DB_CONNECTION_STRING: "server=mysql_bd_Personas;user=usuario;password=PASS333;database=Personas"
         
volumes:
  bd_volumen_personas: